name: Bug Report
description: Use this when the plugin breaks something
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        Explain both the bug and how to reproduce it.
        Also, you can put the error logs on here.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expect to happen.
    validations:
      required: true
  - type: input
    id: repro-link
    attributes:
      label: Reproduction link
      description: Leave URL of the repository or playground if it exists
  - type: input
    id: version
    attributes:
      label: Version
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Config
      description: Paste your plugin options in `next.confing.js` here.
      render: javascript
  - type: textarea
    id: addition
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
